packages:
  - "packages/extenzo"
  - "packages/cli"
  - "packages/core"
  - "packages/utils"
  - "packages/plugins/plugin-entry"
  - "packages/plugins/plugin-extension"
  - "packages/plugins/plugin-hmr"
  - "packages/plugins/plugin-vue"
  - "packages/create-extenzo-app"
  - "docs"
  - "examples/*"
