packages:
  - "packages/extenzo"
  - "packages/cli"
  - "packages/core"
  - "packages/utils"
  - "packages/plugins/plugin-extension-entry"
  - "packages/plugins/plugin-extension-manifest"
  - "packages/plugins/plugin-extension-hmr"
  - "packages/plugins/plugin-extension-monitor"
  - "packages/plugins/plugin-vue"
  - "packages/create-extenzo-app"
  - "docs"
  - "examples/*"
